# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'deploy.sh']
markdown: rdiscount

# configuration required for some pages

domain: www.simpledev.com.br
title: SimpleDev - Simplificando o Desenvolvimento de Software
author: Juliano Alves
email: von.juliano@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-33493244-1

# github:
#   username: ghusername

disqus:
  id: simpledevcombr
